

name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Prepare for Yarn Installation

              
      - name: Install Surge
        run: npm install -globle surge

      - name: Build React App
        run: npm run build

      - name: Run surge
        run: surge ./build react_app_1.surge.sh --token ${{ secrets.SURGE_TOKEN }}
